name: Publish nightly lang pack

on:
  workflow_call:
    inputs:
      target_lang:
        description: "Target language to run"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      target_lang:
        description: "Target language to run"
        required: true
        type: choice
        options:
          - zh_CN
          - ja_JP
          - ko_KR
          - pt_BR
          - fr_FR
          - es_ES
          - tr_TR
          - de_DE

env:
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}

jobs:
  nightly-build:
    name: Nightly Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push commits and tag
        run: |
          git config pull.ff only
          git pull
          git push -d origin ${{ inputs.target_lang }}-latest || :
          gh release delete ${{ inputs.target_lang }}-latest || :
          git tag ${{ inputs.target_lang }}-latest
          git push origin ${{ inputs.target_lang }}-latest
          git push origin master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
