name: Publish all nightly lang packs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ja_JP1:
    uses: ./.github/workflows/publish-nightly-lang-pack.yml
    with:
      target_lang: ja_JP
    secrets: inherit
  ja_JP2:
    uses: ./.github/workflows/publish-nightly-lang-pack.yml
    needs: ja_JP1 # Require previous run to finish
    with:
      target_lang: ja_JP
    secrets: inherit
  ja_JP3:
    uses: ./.github/workflows/publish-nightly-lang-pack.yml
    needs: ja_JP2 # Require previous run to finish
    with:
      target_lang: ja_JP
    secrets: inherit
